Expliclity require 'timeout' from the stdlib
This avoids getting the following error on some platforms:

NameError: uninitialized constant GitlabKeys::Timeout